- id: '1507960736936'
  alias: Laundry finished
  trigger:
  - entity_id: sensor.laundry_plug_status
    for: 00:01:00
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - alias: Gmail
    data:
      message: How dry do you like it?!
      title: Laundry
    service: notify.gmail_sms
  - alias: Kodi
    data:
      message: How dry do you like it?!
      title: Laundry
    service: notify.kodi