- action:
  - alias: Gmail
    data:
      message: How dry do you like it?!
      title: Laundry
    service: notify.gmail_sms
  alias: Laundry done email
  condition: []
  id: '1507960736936'
  trigger:
  - entity_id: sensor.computed_laundry_status
    from: 'True'
    platform: state
    to: 'False'
- action:
  - alias: Front door switch off
    data:
      entity_id: switch.front_door_switch
    service: switch.turn_off
  alias: Front door switch off at sunrise
  condition: []
  id: '1508052370089'
  trigger:
  - event: sunrise
    offset: 00:40:00
    platform: sun
- action:
  - alias: Front door switch on
    data:
      entity_id: switch.front_door_switch
    service: switch.turn_on
  alias: Front door switch on at sunset
  condition: []
  id: '1508103995598'
  trigger:
  - event: sunset
    offset: -00:40:00
    platform: sun
- action:
  - alias: Living room light on
    data:
      brightness: '75'
      entity_id: light.living_room_light_level
      transition: '120'
    service: light.turn_on
  alias: Living room light on at sunset
  condition: []
  id: '1516591514142'
  trigger:
  - event: sunset
    platform: sun
- action:
  - alias: Living room light off
    data:
      entity_id: light.living_room_light_level
      transition: '10'
    service: light.turn_off
  - alias: Living room track off
    data:
      entity_id: light.living_room_track_level
      transition: '4'
    service: light.turn_off
  alias: Living room off at 2:15AM
  condition: []
  id: '1516591813514'
  trigger:
  - at: '2:15:00'
    platform: time
- action:
  - data:
      color_name: red
      entity_id: light.office_light_level
    service: light.turn_on
  alias: Intrusion Detected
  condition:
  - condition: state
    entity_id: light.office_light_level
    state: 'on'
  id: '1521008562125'
  trigger:
  - entity_id: binary_sensor.door_motion
    platform: state
    to: 'on'
- action:
  - data:
      color_name: white
      entity_id: light.office_light_level
    service: light.turn_on
  alias: Intrusion Clear
  condition:
  - condition: state
    entity_id: light.office_light_level
    state: 'on'
  id: '1521009324060'
  trigger:
  - entity_id: binary_sensor.door_motion
    platform: state
    to: 'off'
