- id: '1507960736936'
  alias: Laundry finished
  trigger:
  - entity_id: sensor.laundry_plug_status
    for: 00:01:00
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - alias: Gmail
    data:
      message: How dry do you like it?!
      title: Laundry
    service: notify.gmail_sms
  - alias: Kodi
    data:
      message: How dry do you like it?!
      title: Laundry
    service: notify.kodi
- id: '1521008562125'
  alias: Intrusion detected
  trigger:
  - entity_id: binary_sensor.door_motion
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: light.office_lamp
    state: 'on'
  action:
  - data:
      color_name: red
      entity_id: light.office_lamp
      white_value: '0'
    service: light.turn_on
- id: '1521009324060'
  alias: Intrusion cleared
  trigger:
  - entity_id: binary_sensor.door_motion
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: light.office_lamp
    state: 'on'
  action:
  - data:
      color_name: white
      entity_id: light.office_lamp
      white_value: '255'
    service: light.turn_on
- id: '1525907025405'
  alias: Sync indoor temp with outdoor temp
  trigger:
  - entity_id: sensor.pws_temp_f
    platform: state
  condition: []
  action:
  - data: {}
    service: script.refresh_thermostats
