- id: notification_garage
  alias: Notification - Garage Door
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.jason
    - person.christina
    from: home
    to: not_home
  condition:
  - condition: state
    entity_id: binary_sensor.garage_door
    state: 'on'
  action:
  - service: notify.devices
    data:
      title: Garage Door
      message: '{{ "Someone" if trigger.to_state is undefined else trigger.to_state.attributes.friendly_name
        }} left home and the door is open.'
  mode: single
- id: lights_off_midnight
  alias: Lights off at midnight
  description: ''
  trigger:
  - platform: time
    at: 00:00:00
  condition: []
  action:
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.outside_main_accent
      - light.primary_bedroom_controller
  mode: single
- id: notification_main_door
  alias: Notification - Main Door Lock
  description: ''
  trigger:
  - platform: state
    entity_id:
    - person.jason
    - person.christina
    from: home
    to: not_home
  condition:
  - condition: state
    entity_id: lock.main_door_lock
    state: unlocked
  action:
  - service: notify.devices
    data:
      title: Main Door Lock
      message: '{{ "Someone" if trigger.to_state is undefined else trigger.to_state.attributes.friendly_name
        }} left home and the door is unlocked.'
  mode: single
- id: timer_entryway_light
  alias: Timer - Entryway Light
  description: ''
  trigger:
  - platform: event
    event_type: zwave_js_notification
    event_data:
      node_id: 13
      event_label: Keypad unlock operation
    enabled: false
  - platform: state
    entity_id:
    - binary_sensor.main_door
  - platform: state
    entity_id:
    - binary_sensor.entryway_motion
  condition:
  - condition: template
    value_template: '{% set playing = is_state( ''media_player.media_room_box'', ''playing''
      ) %}

      {% set motion = is_state( ''binary_sensor.entryway_motion'', ''on'' ) %}

      {{ not (playing and motion) }}'
  action:
  - service: script.light_timer
    data:
      light_entity_id: light.entryway_light
      sensor_entity_id: binary_sensor.entryway_motion
      brightness_pct: 40
  mode: single
- id: zwave_primary_bedroom_accent
  alias: Zwave - Primary Bedroom Controller
  description: ''
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 84
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.property_key == "002" and trigger.event.data.value
          == "KeyPressed" }}'
      sequence:
      - service: light.toggle
        data:
          brightness: 1
        target:
          entity_id: light.primary_bedroom_desk_light
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.property_key == "004" and trigger.event.data.value
          == "KeyPressed" }}'
      sequence:
      - service: switch.toggle
        data: {}
        target:
          entity_id: switch.primary_bedroom_office_monitor_switch
  mode: single
- id: zwave_main_stair_accent
  alias: Zwave - Main Stair Accent
  description: ''
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 33
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.property_key == "001" and trigger.event.data.value
          == "KeyPressed3x" }}'
      sequence:
      - service: lock.unlock
        data: {}
        target:
          entity_id: lock.main_door_lock
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.property_key == "002" and trigger.event.data.value
          == "KeyPressed3x" }}'
      sequence:
      - service: lock.lock
        data: {}
        target:
          entity_id: lock.main_door_lock
  mode: single
- id: timer_laundry_light
  alias: Timer - Laundry Light
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.garage_entry_door
  - platform: state
    entity_id:
    - binary_sensor.laundry_sensor_motion
  condition:
  - condition: template
    value_template: '{% set is_motion = is_state( ''binary_sensor.laundry_sensor_motion'',
      ''on'' ) %}

      {% set is_door = is_state( ''binary_sensor.garage_entry_door'', ''on'' ) %}

      {% set is_playing = is_state( ''media_player.media_room_box'', ''playing'' )
      %}

      {% set is_light = is_state( ''light.laundry_light'', ''on'' ) %}

      {% set is_bright = (states( ''sensor.laundry_sensor_illuminance'' )|int(0) >=
      50) and not is_light %}

      {{ not (is_motion and (is_playing or is_bright)) and not (is_door and is_bright)
      }}'
  action:
  - service: script.light_timer
    data:
      light_entity_id: light.laundry_light
      on_when: always
      sensor_entity_id: binary_sensor.laundry_hybrid_sensor
      duration: 60
      brightness_pct: 25
  mode: single
- id: timer_garage_light
  alias: Timer - Garage Light
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.garage_door_opener
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.garage_entry_door
  condition: []
  action:
  - service: script.light_timer
    data:
      light_entity_id: light.garage_light
      duration: 120
      sensor_entity_id: binary_sensor.garage_entry_door
      on_when: always
  mode: single
- id: home_zone_changed
  alias: Home Zone changed
  description: ''
  trigger:
  - platform: state
    entity_id:
    - zone.home
  condition: []
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: zone.home
        above: 0
      sequence:
      - device_id: c04b21ba8b2647aab4729b24b902f2b4
        domain: climate
        entity_id: climate.thermostat
        type: set_preset_mode
        preset_mode: none
    - conditions:
      - condition: numeric_state
        entity_id: zone.home
        below: 1
      sequence:
      - device_id: c04b21ba8b2647aab4729b24b902f2b4
        domain: climate
        entity_id: climate.thermostat
        type: set_preset_mode
        preset_mode: Away
  mode: single
- id: timer_upstairs_hallway_light
  alias: Timer - Upstairs Hallway Light
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.upstairs_hallway_sensor_motion
  condition: []
  action:
  - service: script.light_timer
    data:
      light_entity_id: light.upstairs_hallway_light
      sensor_entity_id: binary_sensor.upstairs_hallway_sensor_motion
      brightness_pct: 15
  mode: single
- id: timer_kitchen_light
  alias: Timer - Kitchen Light
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.kitchen_sensor_motion
  condition: []
  action:
  - service: script.light_timer
    data:
      light_entity_id: light.kitchen_light
      sensor_entity_id: binary_sensor.kitchen_sensor_motion
      duration: 120
  - service: script.light_timer
    data:
      light_entity_id: light.kitchen_pantry_light
      sensor_entity_id: binary_sensor.kitchen_sensor_motion
      on_when: never
  mode: single
- id: timer_main_stair_light
  alias: Timer - Main Stair Light
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.entryway_motion
  condition: []
  action:
  - service: script.light_timer
    data:
      light_entity_id: light.main_stair_light
      on_when: never
      sensor_entity_id: binary_sensor.entryway_motion
  - service: script.light_timer
    data:
      duration: 300
      on_when: never
      light_entity_id: light.main_stair_accent
      sensor_entity_id: binary_sensor.entryway_motion
  mode: restart
- id: generic_light_timer_idle
  alias: Generic Light Timer idle
  description: ''
  trigger:
  - platform: event
    event_type: timer.finished
  condition:
  - condition: template
    value_template: '{{ trigger.event.data.entity_id[-12:] == ''_light_timer'' }}'
  action:
  - service: light.turn_off
    data:
      transition: 15
    target:
      entity_id: light.{{ trigger.event.data.entity_id[6:-6] }}
  mode: queued
  max: 10
- id: timer_upstairs_bathroom_light
  alias: Timer - Upstairs Bathroom Light
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.upstairs_bathroom_hybrid_sensor
    from: 'off'
    to: 'on'
  - platform: state
    entity_id:
    - binary_sensor.upstairs_bathroom_hybrid_sensor
    from: 'on'
    to: 'off'
  condition:
  - condition: template
    value_template: '{% set is_motion = is_state(''binary_sensor.upstairs_bathroom_hybrid_sensor'',
      ''on'') %}

      {% set is_light = is_state( ''light.upstairs_bathroom_light'', ''on'' ) %}

      {% set is_bright = (states( ''sensor.upstairs_bathroom_sensor_illuminance''
      )|int(0) >= 60) and not is_light %}

      {{ not(is_motion and is_bright) }}'
  action:
  - service: script.light_timer
    data:
      light_entity_id: light.upstairs_bathroom_light
      sensor_entity_id: binary_sensor.upstairs_bathroom_hybrid_sensor
      brightness_pct: 50
      on_when: always
      duration: 60
  mode: single
- id: media_room_box_changed
  alias: Media Room Box changed
  description: ''
  trigger:
  - platform: state
    entity_id:
    - media_player.media_room_box
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: media_player.media_room_box
        state: playing
      sequence:
      - service: light.turn_off
        data:
          transition: 2
        target:
          entity_id:
          - light.entryway_light
          - light.laundry_light
      - condition: template
        value_template: '{{ state_attr(''light.media_room_light'', ''brightness'')|int(0)>13
          }}'
      - service: light.turn_off
        data: {}
        target:
          entity_id: light.media_room_light
    - conditions:
      - condition: state
        entity_id: media_player.media_room_box
        state: 'off'
      sequence:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - service: light.turn_on
        data:
          transition: 2
          brightness_pct: 25
        target:
          entity_id:
          - light.entryway_light
          - light.media_room_light
  mode: restart
- id: timer_upstairs_bathroom_fan
  alias: Timer - Upstairs Bathroom Fan
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.upstairs_bathroom_sensor_humidity
  condition: []
  action:
  - if:
    - condition: template
      value_template: '{% set bathroom = states("sensor.upstairs_bathroom_sensor_humidity")|float(0)
        %} {% set main = states("sensor.thermostat_humidity")|float(40) %} {{ bathroom
        >  main + 7.5 }}'
    then:
    - service: fan.turn_on
      data: {}
      target:
        entity_id: fan.upstairs_bathroom_fan
    else:
    - service: fan.turn_off
      data: {}
      target:
        entity_id: fan.upstairs_bathroom_fan
  mode: single
- id: timer_basement_hallway_light
  alias: Timer - Basement Hallway Light
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.basement_hallway_hybrid_sensor
  condition: []
  action:
  - service: script.light_timer
    data:
      light_entity_id: light.basement_stair_light
      on_when: always
      sensor_entity_id: binary_sensor.basement_hallway_hybrid_sensor
      duration: 60
      brightness_pct: 25
  - service: script.light_timer
    data:
      light_entity_id: light.basement_hallway_light
      sensor_entity_id: binary_sensor.basement_hallway_hybrid_sensor
      duration: 60
      brightness_pct: 25
      on_when: dark
  - service: script.light_timer
    data:
      duration: 300
      on_when: never
      light_entity_id: light.basement_stair_accent
      sensor_entity_id: binary_sensor.basement_hallway_hybrid_sensor
  mode: single
- id: timer_kitchen_pantry_light
  alias: Timer - Kitchen Pantry Light
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.kitchen_sensor_motion
  condition: []
  action:
  - service: script.light_timer
    data:
      light_entity_id: light.kitchen_pantry_light
      sensor_entity_id: binary_sensor.kitchen_sensor_motion
      on_when: never
  mode: single
- id: timer_basement_light
  alias: Timer - Basement Light
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.basement_motion
  condition: []
  action:
  - service: script.light_timer
    data:
      light_entity_id: light.basement_light
      sensor_entity_id: binary_sensor.basement_motion
      duration: 300
  mode: single
- id: zwave_kitchen_accent
  alias: Zwave - Kitchen Accent
  description: ''
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 18
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.property_key == "001" and trigger.event.data.value
          == "KeyPressed2x" }}'
      sequence:
      - service: switch.turn_on
        data: {}
        target:
          entity_id: switch.family_room_floor_lamp_switch
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.property_key == "002" and trigger.event.data.value
          == "KeyPressed2x" }}'
      sequence:
      - service: switch.turn_off
        data: {}
        target:
          entity_id: switch.family_room_floor_lamp_switch
  mode: single
- id: zwave_media_room_light
  alias: Zwave - Media Room Light
  description: ''
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 30
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.property_key == "001" and trigger.event.data.value
          == "KeyPressed3x" }}'
      sequence:
      - service: select.select_option
        data:
          option: Watch TV
        target:
          entity_id: select.media_room_remote_activities
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.property_key == "002" and trigger.event.data.value
          == "KeyPressed3x" }}'
      sequence:
      - service: select.select_option
        data:
          option: PowerOff
        target:
          entity_id: select.media_room_remote_activities
  mode: single
- id: zwave_basement_light
  alias: Zwave - Basement Light
  description: ''
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 60
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.property_key == "001" and trigger.event.data.value
          == "KeyPressed3x" }}'
      sequence:
      - service: automation.turn_on
        data: {}
        target:
          entity_id:
          - automation.timer_basement_light
          - automation.timer_basement_hallway_light
      - service: light.turn_on
        data: {}
        target:
          entity_id:
          - light.basement_light
          - light.basement_hallway_light
          - light.basement_stair_light
      - service: timer.start
        data:
          duration: 0
        target:
          entity_id:
          - timer.basement_light_timer
          - timer.basement_hallway_light_timer
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.property_key == "002" and trigger.event.data.value
          == "KeyPressed3x" }}'
      sequence:
      - service: automation.turn_off
        data:
          stop_actions: true
        target:
          entity_id:
          - automation.timer_basement_light
          - automation.timer_basement_hallway_light
      - service: light.turn_off
        data: {}
        target:
          entity_id:
          - light.basement_light
          - light.basement_hallway_light
          - light.basement_stair_light
      - service: timer.cancel
        data: {}
        target:
          entity_id:
          - timer.basement_light_timer
          - timer.basement_hallway_light_timer
  mode: single
- id: tag_main_door
  alias: Tag - Main Door
  description: ''
  trigger:
  - platform: tag
    tag_id: 8c3fcd2a-35a9-424e-a333-2773186667c5
  condition: []
  action:
  - service: lock.unlock
    data: {}
    target:
      entity_id: lock.main_door_lock
  mode: single
- id: timer_media_room_light
  alias: Timer - Media Room Light
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.entryway_motion
  condition:
  - condition: state
    entity_id: media_player.media_room_box
    state: 'off'
  action:
  - service: script.light_timer
    data:
      light_entity_id: light.media_room_light
      sensor_entity_id: binary_sensor.entryway_motion
      on_when: never
      duration: 120
  mode: single
- id: timer_main_hallway_light
  alias: Timer - Main Hallway Light
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.entryway_motion
  condition: []
  action:
  - service: script.light_timer
    data:
      light_entity_id: light.main_hallway_light
      on_when: never
      sensor_entity_id: binary_sensor.entryway_motion
  mode: single
- id: '1669057661233'
  alias: Tag - Office Light
  description: ''
  trigger:
  - platform: tag
    tag_id: 32866474-cc6d-4eeb-a3d7-d3f7a2ff15c9
  condition: []
  action:
  - service: switch.toggle
    data: {}
    target:
      entity_id: switch.office_desk_light
  mode: single
- id: '1669142702191'
  alias: Darkness turns outside lights on
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.estimated_illuminance
    above: 500
  - platform: numeric_state
    entity_id: sensor.estimated_illuminance
    below: 500
  condition: []
  action:
  - if:
    - condition: numeric_state
      entity_id: sensor.estimated_illuminance
      below: 500
    then:
    - service: scene.turn_on
      target:
        entity_id: scene.outside_lights_on
      data: {}
    else:
    - service: scene.turn_on
      target:
        entity_id: scene.outside_lights_off
      data: {}
  mode: single
- id: '1669409026105'
  alias: Zwave - Office Desk Light Switch
  description: ''
  trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      node_id: 74
  condition: []
  action:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.property_key == "001" and trigger.event.data.value
          == "KeyPressed" }}'
      sequence:
      - service: switch.turn_on
        target:
          entity_id: switch.office_desk_light
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.property_key == "002" and trigger.event.data.value
          == "KeyPressed" }}'
      sequence:
      - service: switch.turn_off
        target:
          entity_id: switch.office_desk_light
  mode: single
- id: '1675194600522'
  alias: Notification - Litter Robot
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.litter_robot_status_code
  condition:
  - condition: template
    value_template: '{{ states( "sensor.litter_robot_status_code" ) not in ["rdy","ccc","ccp","cst",
      "offline"] }}'
  action:
  - service: notify.devices
    data:
      message: '{{ state_attr(''vacuum.litter_robot_litter_box'', ''status'') }}'
      title: Litter Robot
  mode: single
- id: '1676141905184'
  alias: Thermostat is unavailable
  description: ''
  trigger:
  - platform: state
    entity_id:
    - climate.thermostat
    to: unavailable
  condition: []
  action:
  - service: notify.mobile_app_jason_pixel_7
    data:
      message: Thermostat is unavailable.
  mode: single
