homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 172
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config/www

frontend:
  themes: !include themes.yaml

config:

http: !include http.yaml

updater:
  include_used_components: true

discovery:
  # ignore:
    # - roku
    # - harmony

conversation:

history:

logbook:

light: !include lights.yaml

sun:

sensor: !include sensors.yaml

tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml

script: !include scripts.yaml

binary_sensor: !include binary_sensors.yaml

# zwave:
#   usb_path: /dev/ttyACM0

ecobee:
  api_key: !secret ecobee_api_key

# emulated_hue:
#   host_ip: 192.168.0.148

notify: !include notifiers.yaml

device_tracker:
  platform: google_maps
  username: !secret gmail_username
  password: !secret gmail_password

sabnzbd: !include sabnzbd.yaml

camera: !include cameras.yaml

switch: !include switches.yaml

zone: !include zones.yaml

proximity:
  home:
    devices:
      - device_tracker.google_maps_111034445952431641993
      - device_tracker.google_maps_114963797368641553787
    unit_of_measurement: mi

vera:
  vera_controller_url: http://192.168.0.28:3480/
  exclude: [15]

konnected: !include konnected.yaml

# alarm_control_panel:
#   - platform: manual

# media_player: !include media_players.yaml