homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 172
  unit_system: imperial
  time_zone: America/Los_Angeles
  external_url: https://home.hutenosa.com:8123
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config/www
  # auth_providers:
  #   - type: trusted_networks
  #     trusted_networks:
  #       - 192.168.0.0/24


frontend:
  themes: !include themes.yaml

config:

http: !include http.yaml

updater:

discovery:

conversation:

history:

logbook:

light: !include lights.yaml

rest_command: !include rest_command.yaml

sun:

sensor: !include sensors.yaml

tts:
  - platform: google_translate
    service_name: google_say

group: !include groups.yaml

#automation: !include automations.yaml

script: !include scripts.yaml

system_health:

mobile_app:

binary_sensor: !include binary_sensors.yaml

ecobee:
  api_key: !secret ecobee_api_key

notify: !include notifiers.yaml

#camera: !include cameras.yaml

switch: !include switches.yaml

zone: !include zones.yaml

proximity:
  home:
    devices:
      - device_tracker.google_maps_111034445952431641993
      - device_tracker.google_maps_114963797368641553787
    unit_of_measurement: mi

vera:
  vera_controller_url: http://192.168.0.11:3480/

konnected: !include konnected.yaml

alarm_control_panel:
  - platform: manual

media_player: !include media_players.yaml

person:
