homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 172
  customize: !include customize.yaml
  allowlist_external_dirs:
    - /config/www

frontend:
  themes: !include themes.yaml

default_config:

http: !include http.yaml

discovery:

conversation:

recorder:
  exclude:
    entity_globs:
      - sensor.s22_*
      - binary_sensor.s22_*
    entities:
      - script.set_light_timer
    domains:
      - automation

history:

logbook:

light: !include lights.yaml

rest_command: !include rest_command.yaml

sun:

sensor: !include sensors.yaml

tts:
  - platform: google_translate
    service_name: google_say

group: !include groups.yaml

automation: !include automations.yaml

script: !include scripts.yaml

system_health:

mobile_app:

binary_sensor: !include binary_sensors.yaml

ecobee:
  api_key: !secret ecobee_api_key

notify: !include notifiers.yaml

#camera: !include cameras.yaml

switch: !include switches.yaml

zone: !include zones.yaml

proximity:
  home:
    devices:
      - person.jason
      - person.christina
    unit_of_measurement: mi

konnected: !include konnected.yaml

alarm_control_panel:
  - platform: manual

media_player: !include media_players.yaml

person:

template: !include templates.yaml

cover: !include covers.yaml

scene: !include scenes.yaml

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

