homeassistant:
  # Name of the location where Home Assistant is running
  name: Home Assistant
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 172
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Los_Angeles
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:
 ignore:
   - roku
   - plex_mediaserver

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Track the sun
sun:

# Sensors
sensor:
  - platform: template
    sensors:
      computed_laundry_status:
        friendly_name: "Computed Laundry Status"
        value_template: "{{ states.sensor.laundry_power.attributes.power_consumption > 10 }}"
      laundry_status:
        friendly_name: "Laundry"
        value_template: "{% if is_state( 'sensor.computed_laundry_status', 'True' ) %}on{% else %}off{% endif %}"
        icon_template: "{% if is_state( 'sensor.computed_laundry_status', 'True' ) %}mdi:power-plug{% else %}mdi:power-plug-off{% endif %}"
      living_room_remote_status:
        friendly_name: "Living Room TV"
        value_template: "{{ states.remote.living_room.attributes.current_activity }}"
      front_thermostat_battery:
        friendly_name: "Front Thermostat Battery"
        unit_of_measurement: "%"
        value_template: "{{ states.zwave.front_thermostat.attributes.battery_level }}"
      back_thermostat_battery:
        friendly_name: "Back Thermostat Battery"
        unit_of_measurement: "%"
        value_template: "{{ states.zwave.back_thermostat.attributes.battery_level }}"
      front_thermostat_status:
        friendly_name: "Front Thermostat Status"
        value_template: "{{ states.climate.front_thermostat_heating.attributes.operating_state }}"
      back_thermostat_status:
        friendly_name: "Back Thermostat Status"
        value_template: "{{ states.climate.back_thermostat_heating.attributes.operating_state }}"

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml


binary_sensor:
  platform: hikvision
  host: 192.168.0.100
  username: !secret hikvision_username
  password: !secret hikvision_password

zwave:
  usb_path: /dev/ttyACM0

climate:
  - platform: zwave
  
emulated_hue:
  host_ip: 192.168.0.132

notify:
  - name: gmail
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret gmail_username
    encryption: starttls
    username: !secret gmail_username
    password: !secret gmail_password
    recipient:
      - !secret email_recipient1
    sender_name: Home Assistant
  - name: gmail_sms
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret gmail_username
    encryption: starttls
    username: !secret gmail_username
    password: !secret gmail_password
    recipient:
      - !secret sms_recipient1
    sender_name: Home Assistant

device_tracker:
  - platform: ping
    hosts:
      jason: 192.168.0.118