homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 172
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml

frontend:
  themes: !include themes.yaml

config:

http: !include http.yaml

updater:
  include_used_components: true

discovery:
 ignore:
   - roku
   - plex_mediaserver

conversation:

history:

logbook:

sun:

sensor: !include sensors.yaml

tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml

script: !include scripts.yaml

binary_sensor: !include binary_sensors.yaml

zwave:
  usb_path: /dev/ttyACM0

climate:
  - platform: zwave
  
emulated_hue:
  host_ip: 192.168.0.148

notify: !include notifiers.yaml

device_tracker:
  platform: google_maps
  username: !secret gmail_username
  password: !secret gmail_password

sabnzbd: !include sabnzbd.yaml

camera: !include cameras.yaml

switch: !include switches.yaml

zone: !include zones.yaml