homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 172
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  whitelist_external_dirs:
    - /config/www
  # auth_providers:
  #   - type: trusted_networks
  #     trusted_networks:
  #       - 192.168.0.0/24


frontend:
  themes: !include themes.yaml

config:

http: !include http.yaml

updater:
  include_used_components: true

discovery:
  ignore:
    - igd

conversation:

history:

logbook:

light: !include lights.yaml

sun:

sensor: !include sensors.yaml

tts:
  - platform: google

group: !include groups.yaml

#automation: !include automations.yaml

script: !include scripts.yaml

system_health:

binary_sensor: !include binary_sensors.yaml

ecobee:
  api_key: !secret ecobee_api_key

notify: !include notifiers.yaml

device_tracker:
  platform: google_maps
  username: !secret gmail_username
  password: !secret gmail_password

camera: !include cameras.yaml

switch: !include switches.yaml

zone: !include zones.yaml

proximity:
  home:
    devices:
      - device_tracker.google_maps_111034445952431641993
      - device_tracker.google_maps_114963797368641553787
    unit_of_measurement: mi

vera:
  vera_controller_url: http://192.168.0.14:3480/
  lights: [52,53,54]

konnected: !include konnected.yaml

alarm_control_panel:
  - platform: manual
    pending_time: 0

media_player: !include media_players.yaml

person:
  - name: Jason
    id: 1
    user_id: cc4f673a3a1c411291f545210bdcf3b2
    device_trackers:
      - device_tracker.google_maps_111034445952431641993
  - name: Christina
    id: 2
    user_id: 7658fe32e5274233988db3c427078757
    device_trackers:
      - device_tracker.google_maps_114963797368641553787