- platform: template
  covers:
    garage_door:
      friendly_name: 'Garage Door'
      value_template: "{{ is_state('binary_sensor.garage_door_13', 'on') }}"
      open_cover:
        service: script.turn_on
        entity_id: script.open_garage_door
      close_cover:
        service: script.turn_on
        entity_id: script.close_garage_door
      stop_cover:
        service: switch.turn_on
        entity_id: switch.garage_door_opener
      icon_template: "{% if not is_state('binary_sensor.garage_door_13', 'off') %}mdi:garage-open{% else %}mdi:garage{% endif %}"