- platform: monoprice
  port: /dev/ttyUSB0
  zones:
    11:
      name: Media Room Speakers
    12:
      name: Living Room Speakers
    13:
      name: Master Bedroom Speakers
    14:
      name: Deck Speakers
    # 15:
    #   name: Living Room Speakers 2
    # 16:
    #   name: Living Room Speakers 3
  sources:
    5:
      name: House Audio


- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
