- platform: wunderground
  api_key: !secret wunderground_api_key
  name: Outdoor
  monitored_conditions:
    - temp_f


- platform: template
  sensors:
    laundry_plug_status:
      entity_id: sensor.laundry_plug_power
      friendly_name: "Laundry"
      value_template: "{{ 'on' if state_attr( 'sensor.laundry_plug_power', 'power_consumption' ) | int > 10 else 'off' }}"
      icon_template: "{{ 'mdi:power-plug' if state_attr( 'sensor.laundry_plug_power', 'power_consumption' ) | int > 10 else 'mdi:power-plug-off' }}"


    living_room_remote_status:
      entity_id: remote.living_room
      friendly_name: "Living Room TV"
      value_template: "{{ state_attr( 'remote.living_room', 'current_activity' ) }}"


    front_thermostat_battery:
      entity_id: zwave.front_thermostat
      friendly_name: "Front Thermostat Battery"
      unit_of_measurement: "%"
      value_template: "{{ state_attr( 'zwave.front_thermostat', 'battery_level' ) }}"

    back_thermostat_battery:
      entity_id: zwave.back_thermostat
      friendly_name: "Back Thermostat Battery"
      unit_of_measurement: "%"
      value_template: "{{ state_attr( 'zwave.back_thermostat', 'battery_level' ) }}"


    front_thermostat_overview:
      entity_id: zwave.front_thermostat
      friendly_name: "Front Thermostat Overview"
      value_template: "{{ 'OFF' if is_state_attr( 'climate.front_thermostat_heating', 'operation_mode', 'off' ) else 'ON' }}/{{ state_attr( 'climate.front_thermostat_heating', 'operating_state' ) }}  {{ states( 'sensor.front_thermostat_temperature' ) }}째/{{ state_attr( 'climate.front_thermostat_heating', 'temperature' ) }}째"
      icon_template: "{{ 'mdi:thermometer' if is_state_attr( 'climate.front_thermostat_heating', 'operating_state', 'Idle' ) else 'mdi:thermometer-lines' }}"

    back_thermostat_overview:
      entity_id: zwave.back_thermostat
      friendly_name: "Back Thermostat Overview"
      value_template: "{{ 'OFF' if is_state_attr( 'climate.back_thermostat_heating', 'operation_mode', 'off' ) else 'ON' }}/{{ state_attr( 'climate.back_thermostat_heating', 'operating_state' ) }}  {{ states( 'sensor.back_thermostat_temperature' ) }}째/{{ state_attr( 'climate.back_thermostat_heating', 'temperature' ) }}째"
      icon_template: "{{ 'mdi:thermometer' if is_state_attr( 'climate.back_thermostat_heating', 'operating_state', 'Idle' ) else 'mdi:thermometer-lines' }}"


- platform: google_travel_time
  name: Home to Christina's
  api_key: !secret decartert_gmail_google_api_key
  origin: 6411 Fremont Ave N, Seattle, WA
  destination: 11002 12th Avenue SW, Seattle, WA
