- platform: wunderground
  api_key: !secret wunderground_api_key
  name: Outdoor
  monitored_conditions:
    - temp_f


- platform: template
  sensors:
    proximity_home_summary:
      entity_id: proximity.home
      friendly_name: Closest To Home
      value_template: '{{ state_attr( "proximity.home", "nearest" ) + ", " + states( "proximity.home" ) + " mi, " + state_attr( "proximity.home", "dir_of_travel" ) }}'

    # laundry_plug_status:
    #   entity_id: sensor.laundry_plug_power
    #   friendly_name: "Laundry"
    #   value_template: "{{ 'on' if state_attr( 'sensor.laundry_plug_power', 'power_consumption' ) | int > 10 else 'off' }}"
    #   icon_template: "{{ 'mdi:power-plug' if state_attr( 'sensor.laundry_plug_power', 'power_consumption' ) | int > 10 else 'mdi:power-plug-off' }}"

    garbage_collection_summary:
      entity_id: sensor.garbage_collection_summary
      friendly_name: Garbage Collection Summary
      value_template: "{{ state_attr( 'sensor.garbage_collection', 'next_collection_day' ) }} {{ 'with' if state_attr( 'sensor.garbage_collection', 'recycling' ) else 'without' }} recycling"
      icon_template: "{{ 'mdi:recycle' if state_attr( 'sensor.garbage_collection', 'recycling' ) else 'mdi:delete' }}"


    basement_remote_status:
      entity_id: remote.basement
      friendly_name: "Basement Remote Status"
      value_template: "{{ state_attr( 'remote.basement', 'current_activity' ) }}"


    garage_door_sensor_battery:
      entity_id: switch.garage_door_sensor_13
      friendly_name: "Garage Door Sensor Battery"
      unit_of_measurement: "%"
      value_template: "{{ state_attr( 'switch.garage_door_sensor_13', 'battery_level' ) }}"

    # multi_battery:
    #   entity_id: zwave.multi
    #   friendly_name: "Multi Battery"
    #   unit_of_measurement: "%"
    #   value_template: "{{ state_attr( 'zwave.multi', 'battery_level' ) }}"


    # back_thermostat_overview:
    #   entity_id: zwave.back_thermostat
    #   friendly_name: "Back Thermostat Overview"
    #   value_template: "{{ 'OFF' if is_state_attr( 'climate.back_thermostat_heating', 'operation_mode', 'off' ) else 'ON' }}/{{ state_attr( 'climate.back_thermostat_heating', 'operating_state' ) }}  {{ states( 'sensor.back_thermostat_temperature' ) }}°/{{ state_attr( 'climate.back_thermostat_heating', 'temperature' ) }}°"
    #   icon_template: "{{ 'mdi:thermometer' if is_state_attr( 'climate.back_thermostat_heating', 'operating_state', 'Idle' ) else 'mdi:thermometer-lines' }}"


- platform: google_travel_time
  name: Jason work to home
  api_key: !secret decartert_gmail_google_api_key
  origin: 500 Yale Ave N, Seattle, WA
  destination: 6742 38th Ave SW, Seattle, WA

- platform: google_travel_time
  name: Jason home to work
  api_key: !secret decartert_gmail_google_api_key
  origin: 6742 38th Ave SW, Seattle, WA
  destination: 500 Yale Ave N, Seattle, WA


- platform: waze_travel_time
  name: Christina work to home
  origin: 401 Broadway, Seattle, WA
  destination: 6742 38th Ave SW, Seattle, WA
  region: 'US'

- platform: waze_travel_time
  name: Christina home to work
  origin: 6742 38th Ave SW, Seattle, WA
  destination: 401 Broadway, Seattle, WA
  region: 'US'


- platform: command_line
  entity_id: garbage_collection
  name: Garbage Collection
  command: "python3 /config/custom_scripts/garbage_collection.py '6742 38th Ave SW'"
  scan_interval: 1800
  value_template: "{{ value_json.remaining_days }}"
  json_attributes:
    - recycling
    - yard_waste
    - garbage
    - remaining_days
    - next_collection_date
    - next_collection_day
    - address