- platform: template
  switches:
    media_remote:
      entity_id: remote.media
      friendly_name: "Media Remote"
      value_template: "{{ is_state( 'remote.media', 'on' ) }}"
      turn_on:
        service: remote.turn_on
        data:
          entity_id: remote.media
          activity: Watch TV
      turn_off:
        service: remote.turn_off
        data:
          entity_id: remote.media