- platform: template
  switches:
    heat:
      friendly_name: Heat
      value_template: "{{ not is_state_attr( 'climate.back_thermostat_heating', 'operation_mode', 'off' ) or not is_state_attr( 'climate.front_thermostat_heating', 'operation_mode', 'off' ) }}"
      icon_template: "mdi:thermostat"
      turn_on:
        service: script.turn_heat_on
      turn_off:
        service: script.turn_heat_off