sensor:
  - name: Proximity Sensor
    unique_id: proximityhomesensor
    state: '{{ state_attr( "proximity.home", "nearest" ) + ", " + iif( is_state( "proximity.home", "0"), "", states( "proximity.home" ) + " mi, " ) + state_attr( "proximity.home", "dir_of_travel" ) }}'

  - name: Outdoor Temperature Sensor
    unique_id: outdoortemperaturesensor
    state: "{{ state_attr( 'weather.thermostat', 'temperature' ) }}"
    unit_of_measurement: "°F"

  - name: HVAC Status Sensor
    unique_id: hvacstatussensor
    state: >
      {% if state_attr( 'climate.thermostat', 'hvac_action' ) %}
        {{ state_attr( 'climate.thermostat', 'hvac_action' ) + ( ' (with aux)' if state_attr( 'climate.thermostat', 'aux_heat' ) == 'on' else '' ) }}
      {% else %}
        Unavailable
      {% endif %}
    icon: "mdi:thermostat"

  - name: Garbage Pickup Sensor
    unique_id: garbagepickupsummary
    state: >
      {% set now = now().isocalendar() %}
      {{ iif( iif( now[2]>2, (now[1]+1)%2, now[1]%2 ), 'No recycling', 'Recycling') + ' ' + ( 'tomorrow' if now[2]==1 else 'today' if now[2]==2 else 'next Tuesday' ) }}
    icon: >
      {% set now = now().isocalendar() %}
      {{ iif( iif( now[2]>2, (now[1]+1)%2, now[1]%2 ), 'mdi:delete', 'mdi:recycle' ) }}

binary_sensor:
  - name: Upstairs Bathroom Hybrid Sensor
    unique_id: upstairsbathroomhybridsensor
    state: "{{ is_state( 'fan.upstairs_bathroom_fan', 'on' ) or is_state( 'binary_sensor.upstairs_bathroom_sensor_motion', 'on' ) }}"

  - name: Basement Hallway Hybrid Sensor
    unique_id: basementhallwayhybridsensor
    state: "{{ is_state( 'binary_sensor.basement_hallway_sensor_motion', 'on' ) or is_state( 'binary_sensor.basement_stair_sensor_motion', 'on' ) }}"

  - name: Laundry Hybrid Sensor
    unique_id: laundryhybridsensor
    state: "{{ is_state( 'binary_sensor.garage_entry_door', 'on' ) or is_state( 'binary_sensor.laundry_sensor_motion', 'on' ) }}"

  - name: Entryway Motion
    unique_id: entrywaymotion
    state: "{{ is_state( 'binary_sensor.raw_entryway_motion', 'on' ) }}"
    device_class: motion
    delay_off:
      seconds: 10

  - name: Basement Motion
    unique_id: basementmotion
    state: "{{ is_state( 'binary_sensor.raw_basement_motion', 'on' ) }}"
    device_class: motion
    delay_off:
      seconds: 10
