title: Casa de Muy
views:
  - title: Home
    id: home
    cards:
      - type: entities
        title: Climate
        entities:
          - climate.front_thermostat_heating
          - sensor.front_thermostat_status
          - sensor.front_thermostat_battery
          - climate.back_thermostat_heating
          - sensor.back_thermostat_status
          - sensor.back_thermostat_battery

      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - light.living_room_track_level
          - light.living_room_light_level
          - switch.front_door_switch
          - light.office_light_level

      - type: glance
        title: Other Sensors
        show_header_toggle: false
        entities:
          - entity: sensor.laundry_plug_status
            name: Laundry
          - entity: sensor.laundry_plug_power
            name: Laundry Power
          - entity: switch.bedroom_plug_switch
            name: Bedroom
          - entity: sensor.bedroom_plug_power
            name: Bedroom Power

      - type: vertical-stack
        cards:
        - type: glance
          title: Temperatures
          entities:
            - entity: sensor.front_thermostat_temperature
              name: Front
            - entity: sensor.back_thermostat_temperature
              name: Back
            - entity: sensor.pws_temp_f
              name: Outside
        - type: history-graph
          refresh_interval: 300
          hours_to_show: 24
          entities:
            - sensor.front_thermostat_temperature
            - sensor.back_thermostat_temperature
            - sensor.pws_temp_f

      - type: entities
        title: People
        entities:
          - device_tracker.google_maps_111034445952431641993

      - type: glance
        title: Motion Sensors
        entities:
          - binary_sensor.entryway
          - binary_sensor.landing

      - type: entities
        show_header_toggle: false
        title: Media
        entities:
          - sensor.living_room_remote_status
          - remote.living_room

      - type: history-graph
        title: Travel
        refresh_interval: 300
        entities:
          - sensor.home_to_christinas


  - title: Internet
    cards:
      - type: entities
        title: SABnzbd
        entities:
          - sensor.sabnzbd_daily_total
          - sensor.sabnzbd_weekly_total
          - sensor.sabnzbd_monthly_total
          - sensor.sabnzbd_total
          - sensor.sabnzbd_left
          - sensor.sabnzbd_queue
          - sensor.sabnzbd_queue_count
          - sensor.sabnzbd_speed
          - sensor.sabnzbd_status