title: Casa de Muy

views:
  - id: Home  # Automatically created id
    title: Home
    cards:
      - id: 1bf38070b5e645a290f9a1f55d3964ea  # Automatically created id
        type: vertical-stack
        cards:
          - type: entities
            title: Climate
            show_header_toggle: false
            entities:
              - entity: sensor.pws_temp_f
                name: Outside

          - type: history-graph
            title: Temperatures
            refresh_interval: 300
            hours_to_show: 24
            entities:
              - entity: sensor.pws_temp_f
                name: Outside

      - id: aae791faa9994d788f69b9f7e3e930f8  # Automatically created id
        type: entities
        title: People
        entities:
          - device_tracker.google_maps_111034445952431641993
          - device_tracker.google_maps_114963797368641553787

      - id: a1d307ee0eb7487eb6a392ea898971fa  # Automatically created id
        type: entities
        show_header_toggle: false
        title: Media
        entities:
          - sensor.basement_remote_status
          - remote.basement

      - id: 21b2ebfd44f74a359f1aa33dbfe30098  # Automatically created id
        type: history-graph
        title: Travel
        refresh_interval: 300
        entities:
          - sensor.jason_work_to_home

      - id: 31b2ebf344f34a359f13a33dbfe33098  # Automatically created id
        type: entities
        title: Garbage
        entities:
          - entity: sensor.garbage_collection_summary
            name: Gatewood

  - id: Zones  # Automatically created id
    title: Zones
    cards:
      - id: 94310970cd1549d7a5b7408b6e5ccecc  # Automatically created id
        type: map
        aspect_ratio: 125%
        entities:
          - device_tracker.google_maps_111034445952431641993
          - device_tracker.google_maps_114963797368641553787
          - zone.home
          - zone.jason_home
          - zone.jason_work
          - zone.christina_home
          - zone.christina_work
