# sensor.laundry_plug_power:
#   ignored: false
#   polling_intensity: 0
sensor.laundry_plug_current:
  ignored: true
  polling_intensity: 0
sensor.laundry_plug_previous_reading:
  ignored: true
  polling_intensity: 0
switch.laundry_plug_switch:
  ignored: true
  polling_intensity: 0
sensor.laundry_plug_voltage:
  ignored: true
  polling_intensity: 0
sensor.laundry_plug_energy:
  ignored: true
  polling_intensity: 0
climate.front_thermostat_cooling:
  ignored: true
  polling_intensity: 0
climate.back_thermostat_cooling:
  ignored: true
  polling_intensity: 0
